export const COMPANY_ID = "KLKURJA";

export const CONNECTION = {
  basePath: "/api/tally",
  auth: "No login token. Every call must send company_id.",
  contentType: "application/json",
  batch: '{ "data": [ { ... }, { ... } ] } or a raw array [ { ... } ]',
  dates: "02/Jul/2026 or 2026-07-02",
  repost:
    "Posting the same document number again updates that record. It does not return an already-exists error.",
};

export const METHODS = [
  { method: "GET", action: "Export queue", path: "?company_id=KLKURJA" },
  { method: "GET", action: "One record", path: "/{id}?company_id=KLKURJA" },
  { method: "POST", action: "Create or update", path: "?company_id=KLKURJA" },
  { method: "PUT", action: "Update", path: "/{id}?company_id=KLKURJA" },
  { method: "DELETE", action: "Delete", path: "/{id}?company_id=KLKURJA" },
  { method: "PATCH", action: "Mark synced", path: "/{id}/pushed?company_id=KLKURJA" },
];

const companyId = COMPANY_ID;

export const MODULES = [
  {
    id: "purchases",
    title: "Purchase Invoice",
    path: "purchases",
    summary:
      "Purchase bills. Items go in PurchaseItems. Tax lines go in GstDetails. Bank branch and IFSC are stored together and shown on the purchase screen.",
    minimum: ["company_id", "PurchaseNo", "PurchaseDate", "VendorName", "PurchaseItems"],
    notes: [
      "PODate is the purchase order date. ReferenceNoDate is the reference text.",
      "CGST and SGST belong in GstDetails. IGSTRate and IGSTAmount stay on the header.",
      "An empty IRN is filled automatically from the purchase number.",
    ],
    example: {
      data: [
        {
          company_id: companyId,
          InvoiceType: "Tax Invoice",
          IRN: "",
          AckNo: "112233",
          AckDate: "02/Jul/2026",
          PurchaseNo: "Pur0991",
          PurchaseDate: "02/Jul/2026",
          PONo: "PO908",
          PODate: "01/Jul/2026",
          EWayBillNo: "EWB123456",
          DeliveryNote: "DN-01",
          DeliveryNoteDate: "02/Jul/2026",
          ModeTermsOfPayment: "30 Days",
          ReferenceNoDate: "REF-1",
          OtherReferences: "",
          DispatchDocNo: "DISP-1",
          DispatchedThrough: "Road",
          Destination: "Delhi",
          BillOfLadingNo: "",
          MotorVehicleNo: "DL01AB1234",
          TermsOfDelivery: "FOB",
          VendorName: "XYZ Pvt Ltd",
          VendorAddress: "Plot 12, Industrial Area, Gurugram",
          Vendorgstin: "06AAAAA0000A1Z5",
          VendorState: "Haryana",
          VendorStateCode: "06",
          VendorCIN: "U12345HR2020PTC000001",
          VendorEmail: "vendor@xyz.com",
          BankName: "HDFC Bank",
          BankAccountNo: "1234567890",
          BankBranch: "MG Road",
          BankIfsc: "HDFC0001234",
          ConsigneeName: "Consignee Name",
          ConsigneeAddress: "Warehouse address",
          ConsigneeGstin: "07BBBBB0000B1Z5",
          ConsigneeState: "Delhi",
          ConsigneeStateCode: "07",
          ConsigneeEmail: "consignee@mail.com",
          BuyerName: "KLK Ventures",
          BuyerAddress: "Head Office Address",
          BuyerGstin: "07CCCCC0000C1Z5",
          BuyerState: "Delhi",
          BuyerStateCode: "07",
          BuyerPAN: "CCCCC0000C",
          BuyerEmail: "accounts@klk.co.in",
          PurchaseAmount: 120000,
          TaxableValue: 101694.92,
          TotalQuantity: 5,
          TotalTaxAmount: 18305.08,
          IGSTRate: 0,
          IGSTAmount: 0,
          AmountInWords: "One Lakh Twenty Thousand Only",
          TaxAmountInWords: "Eighteen Thousand Three Hundred Five Only",
          Declaration: "We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct.",
          AuthorisedSignatoryName: "Accounts Head",
          AuthorisedSignatoryDesignation: "Manager",
          IssuingSignatoryName: "",
          IssuingSignatoryDesignation: "",
          Jurisdiction: "Delhi",
          PurchaseItems: [
            { itemname: "Item A", hsn_sac: "84713010", quantity: 1, unit: "Nos", rate: 15844, per: "Nos", amount: 15844 },
            { itemname: "Item B", hsn_sac: "39269099", quantity: 4, unit: "Nos", rate: 12000, per: "Nos", amount: 48000 },
          ],
          GstDetails: [
            { LedgerName: "CGST", rate: 9, amount: 5822 },
            { LedgerName: "SGST", rate: 9, amount: 5822 },
          ],
        },
      ],
    },
  },
  {
    id: "sales",
    title: "Sales Invoice",
    path: "sales",
    summary:
      "Sales bills. Customer fields use CustomerName and customergstin. Seller fields use SellerName. Tax can be sent as CGSTRate / SGSTRate / IGSTRate and as GstDetails.",
    minimum: ["company_id", "InvoiceNo", "InvoiceDate", "CustomerName", "BillItems"],
    notes: [
      "BuyersOrderDate is stored as the order date on the sales screen.",
      "DeliveryNote is the delivery note on the sales screen. If DeliveryNote is blank, Challanno is used.",
      "There is no separate GST table. GstDetails are saved as CGST, SGST, and IGST on the invoice.",
    ],
    example: {
      data: [
        {
          company_id: companyId,
          InvoiceType: "Tax Invoice",
          IRN: "",
          AckNo: "",
          AckDate: "",
          InvoiceNo: "Inv0991",
          InvoiceDate: "02/Jul/2026",
          Challanno: "DC-01",
          BuyersOrderNo: "BO-100",
          BuyersOrderDate: "01/Jul/2026",
          EWayBillNo: "",
          DeliveryNote: "",
          DeliveryNoteDate: "",
          ModeTermsOfPayment: "Advance",
          ReferenceNoDate: "",
          OtherReferences: "",
          DispatchDocNo: "",
          DispatchedThrough: "",
          Destination: "Noida",
          BillOfLadingNo: "",
          MotorVehicleNo: "",
          TermsOfDelivery: "",
          SellerName: "KLK Ventures",
          SellerAddress: "Head Office Address",
          SellerGstin: "07CCCCC0000C1Z5",
          SellerState: "Delhi",
          SellerStateCode: "07",
          SellerCIN: "",
          SellerEmail: "accounts@klk.co.in",
          BankName: "HDFC Bank",
          BankAccountNo: "9988776655",
          BankBranch: "CP",
          BankIfsc: "HDFC0001111",
          ConsigneeName: "",
          ConsigneeAddress: "",
          ConsigneeGstin: "",
          ConsigneeState: "",
          ConsigneeStateCode: "",
          ConsigneeEmail: "",
          CustomerName: "ABC Pvt Ltd",
          BuyerAddress: "Customer address",
          customergstin: "09DDDDD0000D1Z5",
          BuyerState: "Uttar Pradesh",
          BuyerStateCode: "09",
          BuyerPAN: "DDDDD0000D",
          BuyerEmail: "buyer@abc.com",
          BillAmount: 118000,
          TaxableValue: 100000,
          TotalQuantity: 10,
          TotalTaxAmount: 18000,
          CGSTRate: 9,
          CGSTAmount: 9000,
          SGSTRate: 9,
          SGSTAmount: 9000,
          IGSTRate: 0,
          IGSTAmount: 0,
          AmountInWords: "",
          TaxAmountInWords: "",
          Declaration: "",
          AuthorisedSignatoryName: "",
          AuthorisedSignatoryDesignation: "",
          IssuingSignatoryName: "",
          IssuingSignatoryDesignation: "",
          Jurisdiction: "",
          BillItems: [
            { itemname: "Product A", hsn_sac: "8471", quantity: 10, unit: "Nos", rate: 10000, per: "Nos", amount: 100000 },
          ],
          GstDetails: [
            { LedgerName: "CGST", rate: 9, amount: 9000 },
            { LedgerName: "SGST", rate: 9, amount: 9000 },
          ],
        },
      ],
    },
  },
  {
    id: "credit-notes",
    title: "Credit Note",
    path: "credit-notes",
    summary: "Sales returns. InvoiceNo is the original sales invoice. Customer fields match the sales invoice.",
    minimum: ["company_id", "CreditNoteNo", "CreditNoteDate", "CustomerName", "BillItems"],
    notes: ["Do not send payment vouchers here. Payment JSON goes to /payments."],
    example: {
      data: [
        {
          company_id: companyId,
          InvoiceType: "Credit Note",
          IRN: "",
          AckNo: "",
          AckDate: "",
          CreditNoteNo: "CN-0991",
          CreditNoteDate: "02/Jul/2026",
          InvoiceNo: "Inv0991",
          InvoiceDate: "01/Jul/2026",
          EWayBillNo: "",
          BuyersOrderNo: "",
          OtherReferences: "",
          DispatchDocNo: "",
          DispatchedThrough: "",
          Destination: "",
          TermsOfDelivery: "",
          SellerName: "KLK Ventures",
          SellerAddress: "Head Office",
          SellerGstin: "07CCCCC0000C1Z5",
          SellerState: "Delhi",
          SellerStateCode: "07",
          SellerCIN: "",
          SellerEmail: "",
          SellerPAN: "",
          ConsigneeName: "",
          ConsigneeAddress: "",
          ConsigneeGstin: "",
          ConsigneeState: "",
          ConsigneeStateCode: "",
          ConsigneeEmail: "",
          CustomerName: "ABC Pvt Ltd",
          BuyerAddress: "Customer address",
          customergstin: "09DDDDD0000D1Z5",
          BuyerState: "Uttar Pradesh",
          BuyerStateCode: "09",
          BuyerPAN: "",
          BuyerEmail: "",
          BillAmount: 11800,
          TaxableValue: 10000,
          TotalQuantity: 1,
          TotalTaxAmount: 1800,
          CGSTRate: 9,
          CGSTAmount: 900,
          SGSTRate: 9,
          SGSTAmount: 900,
          IGSTRate: 0,
          IGSTAmount: 0,
          AmountInWords: "",
          TaxAmountInWords: "",
          AuthorisedSignatoryName: "",
          AuthorisedSignatoryDesignation: "",
          BillItems: [
            { itemname: "Returned item", hsn_sac: "8471", quantity: 1, unit: "Nos", rate: 10000, per: "Nos", amount: 10000 },
          ],
          GstDetails: [
            { LedgerName: "CGST", rate: 9, amount: 900 },
            { LedgerName: "SGST", rate: 9, amount: 900 },
          ],
        },
      ],
    },
  },
  {
    id: "debit-notes",
    title: "Debit Note",
    path: "debit-notes",
    summary: "Purchase adjustments. PurchaseNo is the original purchase bill. Vendor fields match the purchase invoice.",
    minimum: ["company_id", "DebitNoteNo", "DebitNoteDate", "VendorName", "PurchaseItems"],
    notes: [
      "Do not post VoucherNo with DebitLedgers and CreditLedgers to this URL. That JSON belongs on /payments.",
    ],
    example: {
      data: [
        {
          company_id: companyId,
          DebitNoteNo: "DN-0991",
          DebitNoteDate: "02/Jul/2026",
          PurchaseNo: "Pur0991",
          PurchaseDate: "01/Jul/2026",
          OtherReferences: "",
          VendorName: "XYZ Pvt Ltd",
          VendorAddress: "Vendor address",
          Vendorgstin: "06AAAAA0000A1Z5",
          VendorState: "Haryana",
          VendorStateCode: "06",
          VendorCIN: "",
          VendorEmail: "",
          VendorPAN: "",
          ConsigneeName: "",
          ConsigneeAddress: "",
          ConsigneeGstin: "",
          ConsigneeState: "",
          ConsigneeStateCode: "",
          ConsigneeEmail: "",
          BuyerName: "KLK Ventures",
          BuyerAddress: "Head Office",
          BuyerGstin: "07CCCCC0000C1Z5",
          BuyerState: "Delhi",
          BuyerStateCode: "07",
          BuyerPAN: "",
          BuyerEmail: "",
          DebitNoteAmount: 11800,
          TaxableValue: 10000,
          TotalQuantity: 1,
          TotalTaxAmount: 1800,
          CGSTRate: 9,
          CGSTAmount: 900,
          SGSTRate: 9,
          SGSTAmount: 900,
          IGSTRate: 0,
          IGSTAmount: 0,
          AmountInWords: "",
          AuthorisedSignatoryName: "",
          AuthorisedSignatoryDesignation: "",
          PurchaseItems: [
            { itemname: "Debit item", hsn_sac: "8471", quantity: 1, unit: "Nos", rate: 10000, per: "Nos", amount: 10000 },
          ],
          GstDetails: [
            { LedgerName: "CGST", rate: 9, amount: 900 },
            { LedgerName: "SGST", rate: 9, amount: 900 },
          ],
        },
      ],
    },
  },
  {
    id: "delivery-challans",
    title: "Delivery Challan",
    path: "delivery-challans",
    summary: "Delivery challans. Line items use the key challanitems.",
    minimum: ["company_id", "Challanno", "Challandate", "CustomerName", "challanitems"],
    notes: ["GstDetails may be an empty array when the challan has no tax."],
    example: {
      data: [
        {
          company_id: companyId,
          Challanno: "DC0991",
          Challandate: "02/Jul/2026",
          ReferenceNo: "REF-1",
          ReferenceDate: "02/Jul/2026",
          InvoiceNo: "Inv0991",
          InvoiceDate: "02/Jul/2026",
          BuyersOrderNo: "BO-1",
          BuyersOrderDate: "01/Jul/2026",
          DispatchDocNo: "",
          DispatchedThrough: "Courier",
          Destination: "Noida",
          MotorVehicleNo: "",
          BillOfLadingNo: "",
          TermsOfDelivery: "",
          PolicyNo: "",
          PlaceOfSupply: "Uttar Pradesh",
          SellerName: "KLK Ventures",
          SellerAddress: "Head Office",
          SellerGstin: "07CCCCC0000C1Z5",
          SellerState: "Delhi",
          SellerStateCode: "07",
          SellerEmail: "",
          CustomerName: "ABC Pvt Ltd",
          BuyerAddress: "Customer address",
          customergstin: "09DDDDD0000D1Z5",
          BuyerState: "Uttar Pradesh",
          BuyerStateCode: "09",
          Challanamount: 50000,
          TaxableValue: 50000,
          TotalQuantity: 5,
          TotalTaxAmount: 0,
          CGSTRate: 0,
          CGSTAmount: 0,
          SGSTRate: 0,
          SGSTAmount: 0,
          IGSTRate: 0,
          IGSTAmount: 0,
          AmountInWords: "",
          AuthorisedSignatoryName: "",
          AuthorisedSignatoryDesignation: "",
          challanitems: [
            { itemname: "Item A", hsn_sac: "8471", quantity: 5, unit: "Nos", rate: 10000, per: "Nos", amount: 50000 },
          ],
          GstDetails: [],
        },
      ],
    },
  },
  {
    id: "expenses",
    title: "Expense (Journal Voucher)",
    path: "expenses",
    summary:
      "Accounts journal / expense vouchers. This is not the staff expense payment list. DebitLedgers and CreditLedgers must balance.",
    minimum: ["company_id", "VoucherNo", "DebitLedgers", "CreditLedgers"],
    notes: [
      "Sum of DebitLedgers.Amount must equal sum of CreditLedgers.Amount.",
      "GET returns only software vouchers that are Approved and Push to Tally.",
    ],
    example: {
      data: [
        {
          company_id: companyId,
          VoucherNo: "0012",
          VoucherDate: "02/Jul/2026",
          VoucherType: "Expense Voucher",
          CompanyName: "KLK Ventures",
          CompanyAddress: "Head Office",
          CompanyState: "Delhi",
          CompanyStateCode: "07",
          CompanyCIN: "",
          CompanyEmail: "accounts@klk.co.in",
          PayeeType: "COMPANY",
          PayeeName: "Travel Agency",
          PayeeAddress: "",
          PayeeState: "",
          PayeeStateCode: "",
          PayeeGstin: "",
          PayeeEmail: "",
          PayeeDesignation: "",
          Narration: "Travelling and accommodation for project visit",
          OnAccountOf: "Field visit Jul 2026",
          AuthorisedSignatoryName: "",
          AuthorisedSignatoryDesignation: "",
          DebitLedgers: [
            { LedgerName: "Travelling Expenses", Amount: 10000 },
            { LedgerName: "Accomodation Charges", Amount: 3000 },
          ],
          CreditLedgers: [
            { LedgerName: "Cash", Amount: 8000 },
            { LedgerName: "UPI", Amount: 5000 },
          ],
        },
      ],
    },
  },
  {
    id: "payments",
    title: "Payment Voucher",
    path: "payments",
    summary: "Supplier and general payments. Use this URL for voucher JSON with DebitLedgers and CreditLedgers.",
    minimum: ["company_id", "VoucherNo", "DebitLedgers", "CreditLedgers"],
    notes: [
      "Debit and credit totals must match.",
      "Allocations tie the payment to a purchase or other posted document. document_id is the KLK record id.",
    ],
    example: {
      data: [
        {
          company_id: companyId,
          VoucherNo: "0089",
          VoucherDate: "02/Jul/2026",
          PaymentType: "GENERAL",
          PaymentMode: "BANK",
          Narration: "paid to XYZ and ABC",
          OnAccountOf: "Against purchase bills",
          FromCompanyName: "KLK Ventures",
          FromCompanyAddress: "Head Office",
          FromCompanyGstin: "07CCCCC0000C1Z5",
          PayeeType: "COMPANY",
          PartyName: "XYZ Pvt Ltd",
          PartyGstin: "06AAAAA0000A1Z5",
          PartyAddress: "Vendor address",
          LinkedDocumentType: "PURCHASE",
          LinkedDocumentNo: "Pur0991",
          BankName: "HDFC Bank",
          BankAccountNo: "9988776655",
          BankIfsc: "HDFC0001111",
          ReferenceNo: "UTR123456",
          ChequeNo: "",
          ChequeDate: "",
          AuthorisedSignatoryName: "",
          AuthorisedSignatoryDesignation: "",
          DebitLedgers: [
            { LedgerName: "XYZ Imprest A/c", Amount: 13000 },
            { LedgerName: "ABC Imprest A/c", Amount: 5000 },
          ],
          CreditLedgers: [{ LedgerName: "HDFC Bank", Amount: 18000 }],
          Allocations: [
            {
              document_type: "PURCHASE",
              document_id: 12,
              document_no: "Pur0991",
              document_amount: 18000,
              paid_amount: 18000,
              allocation_type: "FULL",
              remarks: "",
            },
          ],
        },
      ],
    },
  },
  {
    id: "companies",
    title: "Company Master",
    path: "companies",
    summary: "Customer and vendor ledgers, including address, tax numbers, and bank accounts.",
    minimum: ["company_id", "CompanyName or LedgerName"],
    notes: [
      "LedgerCode, address, and PIN are filled automatically when they are missing.",
      "Posting the same LedgerCode again updates that company.",
      "BankAccounts replace the previous bank list for that company.",
    ],
    example: {
      data: [
        {
          company_id: companyId,
          CompanyName: "ABC Company",
          LedgerName: "Customer 1",
          LedgerCode: "Cust 001",
          LedgerGroup: "Sundry Debtors",
          ShortName: "ABC",
          AddLine1: "12 MG Road",
          AddLine2: "Near Metro",
          AddLine3: "",
          City: "Delhi",
          LedState: "Delhi",
          LedCountry: "India",
          LedgerPIN: "110001",
          StateCode: "07",
          ContactPerson: "ABC",
          ContactNumber: "9999999999",
          EmailID: "abc@gmail.com",
          PanNumber: "AAAAA1111A",
          GSTNumber: "07AAAAA1111A1Z1",
          TAN: "",
          CIN: "",
          Status: 1,
          BankAccounts: [
            {
              BankName: "HDFC Bank",
              AccountNo: "1234567890",
              BranchName: "Connaught Place",
              IFSC: "HDFC0001234",
              IsPrimary: true,
            },
          ],
        },
      ],
    },
  },
  {
    id: "expense-payments",
    title: "Staff Expense Payments",
    path: "expense-payments",
    readOnly: true,
    summary:
      "Fully paid staff expenses. KLK creates these from Accounts → Pay. Tally can only list them and mark them synced.",
    minimum: ["company_id"],
    notes: [
      "GET returns records that are fully paid and Push to Tally.",
      "There is no POST. Create the payment inside KLK.",
    ],
    example: {
      data: [
        {
          id: 12,
          company_id: companyId,
          DataSource: "Software",
          TallyPushStatus: "PUSHED",
          VoucherNo: "0012",
          VoucherDate: "02/Jul/2026",
          Narration: "remarks | Project: Demo | Intervention: Travelling Expenses",
          DebitLedgers: [{ LedgerName: "Travelling Expenses", Amount: 13000 }],
          CreditLedgers: [
            { LedgerName: "Cash", Amount: 8000 },
            { LedgerName: "UPI", Amount: 5000 },
          ],
        },
      ],
    },
  },
];
